["AppData/Local/nvim-alexis12119"]
type = "git-repo"
url = "git@github.com:KevinNitroG/Alexis12119-nvim.git"

["AppData/Local/LazyVim"]
type = "git-repo"
url = "git@github.com:KevinNitroG/LazyVim-Starter.git"

["AppData/Local/NvChad"]
type = "git-repo"
url = "git@github.com:KevinNitroG/NvChad-Starter.git"

["AppData/Roaming/alacritty/catppuccin-alacritty"]
type = "git-repo"
url = "https://github.com/catppuccin/alacritty.git"

["AppData/Local/SilentCMD/SilentCMD.exe"]
type = "archive-file"
url = "https://github.com/stbrenner/SilentCMD/releases/latest/download/SilentCMD.zip"
path = "SilentCMD.exe"

[".config/cursor/Windows-11-Cursor-by-rosea92"]
type = "git-repo"
url = "https://github.com/YT-Advanced/Windows-11-Cursor-by-rosea92.git"

[".config/wakatime/posh-wakatime"]
type = "git-repo"
url = "https://github.com/Gravifer/posh-wakatime.git"

[".config/windows-terminal/windows-terminal-shaders"]
type = "git-repo"
url = "https://github.com/Hammster/windows-terminal-shaders.git"
