[".config/autohotkey/komorebic.lib.ahk"]
type = "file"
url = "https://raw.githubusercontent.com/LGUG2Z/komorebi/master/komorebic.lib.ahk"

[".config/autohotkey/hidecursor.ahk"]
type = "file"
url = "https://raw.githubusercontent.com/steveseguin/hide-cursor/refs/heads/main/hidecursor.ahk"
