decoration {
  blur {
    enabled = true
  }
  shadow {
    enabled = false
  }
}

input {
    touchpad {
      natural_scroll = yes
	    scroll_factor = 0.1
    }
    force_no_accel = 1
    scroll_factor = 0.6
    follow_mouse = 1
}

cursor {
  # hide_on_key_press	= yes
  inactive_timeout = 10
}

xwayland {
    force_zero_scaling = true
}

misc {
  vfr = false
  key_press_enables_dpms = true
  mouse_move_enables_dpms = false
}

# exec-once = gammastep-indicator
# exec-once = tmux start-server
exec-once = eval "$(ssh-agent -s)"
exec-once = fcitx5
# exec-once = zsh -l -c "tmux has-session &>/dev/null || tmux new-session -d"

# Use hyprctl clients to list apps info
exec-once=[workspace 1 silent] $browser
exec-once=[workspace special silent] $term -e 'zsh -l -c "tmux has-session &>/dev/null && tmux attach || tmux new-session"'

# UTILS
# exec-once = dbus-update-activation-environment --systemd --all
# exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
