#:schema https://raw.githubusercontent.com/yazi-rs/schemas/refs/heads/main/schemas/yazi.json

# https://github.com/timseriakov/dotfiles/blob/master/yazi/yazi-default.toml

[mgr]
show_hidden = true
show_symlink = true
linemode = "size"

[plugin]
prepend_previewers = [
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]
# prepend_fetchers = [
#   { id = "git", name = "*", run = "git", group = "git" },
#   { id = "git", name = "*/", run = "git", group = "git" },
# ]


[opener]
edit = [
  { run = '$EDITOR "%s"', block = true, for = "unix" },
  { run = "%EDITOR% %s", block = true, for = "windows" },
]
extract = [
  { run = 'ouch decompress --yes %s', desc = "Extract here with ouch" },
  # TODO: I cannot make it work with this below
  # { run = 'ya pub extract --list "%s"', desc = "Extract here" },
]
