color_theme = "/home/kevinnitro/.config/btop/themes/catppuccin.theme"
theme_background = true
truecolor = true
vim_keys = true
disable_mouse = false
rounded_corners = true
terminal_sync = true
update_ms = 2000
proc_sorting = "cpu direct"
