name: Test Install

on:
  push:
    branches:
      - main

env:
  BIN_PATH: ${{ github.workspace }}/bin
  INIT_ARGS: >
    --depth=1
    --promptDefaults
    --no-tty
    --color=false
  APPLY_ARGS: >
    --exclude=encrypted,externals,scripts
    --keep-going
    --parent-dirs
    --use-builtin-diff
    --no-pager
    --no-tty
    --color=false
  DOCTOR_ARGS: >
    --keep-going
    --no-tty
    --color=false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    steps:
      - name: Install chezmoi
        shell: bash
        run: bash <(curl -fsLS get.chezmoi.io) -b '${{ env.BIN_PATH }}'

      - name: Export ${{ env.BIN_PATH }} to GITHUB_PATH
        shell: bash
        run: echo '${{ env.BIN_PATH }}' >> "$GITHUB_PATH"

      - name: Init chezmoi
        shell: bash
        run: chezmoi init ${{ github.repository_owner }} ${{ env.INIT_ARGS }}

      # - name: Chezmoi apply
      #   shell: bash
      #   run: chezmoi apply ${{ env.APPLY_ARGS }}

      # - name: Chezmoi doctor
      #   shell: bash
      #   run: chezmoi doctor ${{ env.DOCTOR_ARGS }} || true

      - name: Check all template
        shell: bash
        run: |
          cd "$HOME/.local/share/chezmoi"
          tmpls=$(find . -type f -name "*.tmpl" ! -name ".chezmoi.toml.tmpl" ! -name "rclone.conf.tmpl")
          for tmpl in "${tmpls[@]}"; do
            chezmoi execute-template < "$tmpl" &>/dev/null
            if [ $? -ne 0 ]; then
              echo "$tmpl: Template error" 1>&2
            fi
          done
