name: Test Install

on:
  push:
    branches:
      - main

env:
  BIN_PATH: ${{ github.workspace }}/bin
  INIT_ARGS: >
    --source ${{ github.workspace }}/chezmoi
    --destination ${{ github.workspace }}/dotfiles
    --apply
    --depth 1
    --exclude=encrypted
    --exclude=externals
    --exclude=scripts
    --promptDefaults
    --no-tty
    --color=false
    --verbose
  DOCTOR_ARGS: >
    --source ${{ github.workspace }}/chezmoi
    --destination ${{ github.workspace }}/dotfiles
    --keep-going 
    --no-tty
    --color=false
    --verbose

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows
          - ubuntu
          - macos
    runs-on: ${{ matrix.os }}-latest
    name: Test on ${{ matrix.os }}
    steps:
      - name: Install chezmoi
        shell: bash
        run: bash <(curl -fsLS get.chezmoi.io) -b ${{ env.BIN_PATH }}
      - name: Init chezmoi
        shell: bash
        run: ${{ env.BIN_PATH }}/chezmoi init ${{ github.repository_owner }} ${{ env.INIT_ARGS }}
      - name: Chezmoi doctor
        shell: bash
        run: ${{ env.BIN_PATH }}/chezmoi doctor ${{ env.DOCTOR_ARGS }}
